---
title: "GSEA"
author: "tobiasst"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    df_print: paged
    toc: true 
    toc_depth: 3
    number_sections: true  ## if you want number sections at each table header
    code_folding: hide
    css: share/custom.css

---

http://bioinf.wehi.edu.au/software/MSigDB/index.html

```{r}
library(fgsea)
library(org.Hs.eg.db)
results <- readRDS("res_HD_NSC_v_C116_NSC.rds")
results.ord <- results[ order(-results[,"log2FoldChange"]), ]
ranks <- results.ord$log2FoldChange
names(ranks) <- mapIds(org.Hs.eg.db, keys = rownames(results.ord), keytype = "ENSEMBL",
       column = "ENTREZID", multiVals = "first")
head(ranks)
barplot(ranks)
load("share/human_H_v5p2.rdata")
pathways <- Hs.H

fgseaRes <- fgsea(pathways, ranks, minSize=15, maxSize = 500, nperm=1000)
class(fgseaRes)
dim(fgseaRes)
head(fgseaRes[order(padj), ])


plotEnrichment(pathways[["HALLMARK_E2F_TARGETS"]], ranks)


topPathwaysUp <- fgseaRes[ES > 0][head(order(pval), n=10), pathway]
topPathwaysDown <- fgseaRes[ES < 0][head(order(pval), n=10), pathway]
topPathways <- c(topPathwaysUp, rev(topPathwaysDown))
plotGseaTable(pathways[topPathways], ranks, fgseaRes, 
              gseaParam = 0.5)

```

```{r}
load("share/human_c2_v5p2.rdata")
pathways <- Hs.c2

fgseaRes <- fgsea(pathways, ranks, minSize=15, maxSize = 500, nperm=1000)
head(fgseaRes[order(padj), ])

plotEnrichment(pathways[["KEGG_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY"]], ranks)

topPathwaysUp <- fgseaRes[ES > 0][head(order(pval), n=10), pathway]
topPathwaysDown <- fgseaRes[ES < 0][head(order(pval), n=10), pathway]
topPathways <- c(topPathwaysUp, rev(topPathwaysDown))
plotGseaTable(pathways[topPathways], ranks, fgseaRes, 
              gseaParam = 0.5)

```


```{r}
sessionInfo()
```

